version: "3"
services:
  hodlstream:
    build: .
    image: ${REGISTRY}hodlstream:${CIRCLE_SHA1:-latest}
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      REACT_APP_GA: ${REACT_APP_GA}
      REACT_APP_GRAPHQL: ${REACT_APP_GRAPHQL}
      REACT_APP_SUBSCRIBERS: ${REACT_APP_SUBSCRIBERS}
      REACT_APP_GOOGLE_AD_CLIENT: ${REACT_APP_GOOGLE_AD_CLIENT}
      REACT_APP_FB_APP_ID: ${REACT_APP_FB_APP_ID}
      REACT_APP_STRIPE_KEY: ${REACT_APP_STRIPE_KEY}
