version: '3'
services:
  hodlstream:
    image: ${REGISTRY}hodlstream:${CIRCLE_SHA1:-latest}
    ports:
      - "80:3000"
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      REACT_APP_GA: ${REACT_APP_GA}
      REACT_APP_GRAPHQL: ${REACT_APP_GRAPHQL}